### ISSUE TITLE
error: %MatchError{term: :notok}

### ISSUE THREAD

**Issue by nicomihalich** [nicomihalich/trashcan#32]
`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 🤔

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 🙄

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😯

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😮

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😯

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😓

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😩

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😠

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😡

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😡

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😡

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 💀

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 😩

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 💀

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```

**Comment by nicomihalich** [comment]
Occurred again! 💀

`MyApi.PageController:index/2:web/controllers/page_controller.ex:5`

**Stack Trace**:
  ```
  ** (MatchError) no match of right hand side value: :notok
    (my_api) web/controllers/page_controller.ex:5: MyApi.PageController.index/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.action/2
    (my_api) web/controllers/page_controller.ex:1: MyApi.PageController.phoenix_controller_pipeline/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.instrument/4
    (my_api) lib/phoenix/router.ex:261: MyApi.Router.dispatch/2
    (my_api) web/router.ex:1: MyApi.Router.do_call/2
    (my_api) lib/plug/error_handler.ex:64: MyApi.Router.call/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.phoenix_pipeline/1
    (my_api) lib/plug/debugger.ex:123: MyApi.Endpoint."call (overridable 3)"/2
    (my_api) lib/my_api/endpoint.ex:1: MyApi.Endpoint.call/2
    (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
    (cowboy) /Users/nicomihalich/code/dockyard/lonestarelixir/demo/my_api/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

  ```
